name: dispatch target file updated
on:
  push:
    branches:
      - main
    paths:
      - 'TILs/**'
jobs:
  dispatch-target-updated:
    strategy:
      matrix:
        repo: ['IzmYuta/TIL_calendar']
    name: dispatch-target-updated
    runs-on: ubuntu-latest
    steps:
      - name: dispatch target-updated
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TIL_GITHUB_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: target-updated
